### ISSUE TITLE
Command line usage does nothing

### ISSUE THREAD

**Issue by hawktank** [scrazzz/redgifs#19]
### Summary

Command line usage with a URL does nothing, no error / nothing saved

### Reproduction Steps

The example scripts work but the command line usage of 'redgifs [url]'  does nothing, tried several search query URLs.

### Expected Result

A query output 

### Actual Result

Nothing

### System Information

Window 10 - latest python

### Checklist

- [X] I have searched all open and closed issues for any duplicates.

**Comment by scrazzz** [comment]
The `url` in `redgifs [url]` must be a URL that loads a GIF/video.

Entering anything else should show you an error. Please let me know what version of redgifs you are using (`python3 -m redgifs --version`).

Also let me know what `[url]` you have entered, it would help me a lot since RedGifs changes some stuff in their backend that breaks a lot of things.

**Comment by scrazzz** [comment]
Maybe I should print something that says "Download complete", but I just tested and it downloads for me fine.

![rgshot](https://github.com/scrazzz/redgifs/assets/70033559/358722cb-9390-45ef-af8c-0badfc93dc6a)

**Comment by scrazzz** [comment]
Closed due to inactivity.
