### ISSUE TITLE
Bad request signature.

### ISSUE THREAD

**Issue by kellyaka** [scrazzz/redgifs#32]
### Summary

When trying to open hd/sd links in browser they give: Bad request signature error

### Reproduction Steps

- tried getting gifs with search/search_gifs/get_trending_gifs etc functions
- opened hd link in browser gave bad request signature error
- tried sd link same issue
- tried vthumbnail same issue

### Expected Result

Expected: A video/mp4 file

### Actual Result

Bad request signature.

### System Information

- Python v3.10.5-final
- redgifs v1.9.0-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched all open and closed issues for any duplicates.

**Comment by scrazzz** [comment]
You can't open that link in your browser because RedGifs does some validation based on the URL parameters.

You have 2 options:
1. You can either use the [`API.download()`](https://redgifs.readthedocs.io/en/stable/api.html#redgifs.API.download) method to download the GIF on your device.
2. Or, you can use the `web_url` or `file_url` attribute(s) instead of `sd`, `hd` to view the GIF in your browser. See the note here: https://redgifs.readthedocs.io/en/stable/api.html#redgifs.models.URL

Since you want to see the GIF on your browser, you'll have to go with option 2
