### ISSUE TITLE
Add support for using client token auth

### ISSUE THREAD

**Issue by jehannes** [scrazzz/redgifs#33]
### Summary

i would like to use other tokens than guest to aviod exceeding limits

### The Problem

the redgifs documentation suggests a stringent limit for temporary tokens. https://github.com/Redgifs/api/wiki/Temporary-tokens. using other tokens would solve this

### The Ideal Solution

ideally both client and user tokens (probably by login) would be able to be used. but user tokens would be good enough

### The Current Solution

current solution is to not use this package and implement the auth flow

**Comment by scrazzz** [comment]
Hey, thanks for bringing up this issue. I did decide to implement the [client token auth](https://github.com/Redgifs/api/wiki/Temporary-tokens) but decided to not because redgifs denied my request for a token. So I won't be implementing that anytime soon unless someone helps out by submitting a PR by having a prior discussion about it on Discord.

I can't implement a user token auth (login method) because there's a captcha to complete before logging in which is difficult to do programmatically.

**Comment by scrazzz** [comment]
> wouldn't it be possible to put the website for the captcha in the command line so a user can click it and do the captcha?

No, it doesn't work like that.

I could ask a user to submit the captcha result (a token that is generated once you complete the captcha) but it involves opening your dev console, a.k.a inspect element option on your browser which isn't desirable for a "normal" user.
